server:
  port: 3000

spring:
  mvc:
    static-path-pattern: /public/**
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

  neo4j:
    authentication:
      username: neo4j
      password: password

springdoc:
  swagger-ui:
    enabled: false

springfox:
  documentation:
    enabled:

jwt:
  secret: "secret"